<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Leyla">

<title>Project 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Project 2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Project 2_files/libs/quarto-html/quarto.js"></script>
<script src="Project 2_files/libs/quarto-html/popper.min.js"></script>
<script src="Project 2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Project 2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Project 2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Project 2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Project 2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Project 2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Project 2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Leyla </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Healthcare costs vary not only by smoking habits but also by other personal characteristics such as age, body mass index (BMI), and region of residence. Older individuals, for instance, generally face higher medical expenses, while higher BMI values are linked to obesity-related conditions. Regional differences may also reflect variations in healthcare prices and lifestyle patterns.</p>
<p>The goal of this project is to build a <strong>multivariable regression model</strong> to explain how demographic and lifestyle factors - specifically <strong>age</strong>, <strong>BMI</strong>, <strong>number of children</strong>, <strong>smoker status</strong>, <strong>sex</strong>, and <strong>region</strong> - affect <strong>medical insurance charges</strong>. By including several predictors at once, we can see not only whether each variable matters, but also whether its effect remains important after accounting for the others.</p>
<p>In my first project I examined only smoking status and found that smokers paid much higher charges. In this second project I extend that analysis by including additional predictors such as age, BMI, number of children, sex, and region. This allows me to see whether smoking remains an important factor even after adjusting for other influences</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>The dataset comes from the <strong>Medical Insurance Cost Dataset</strong> available on Kaggle.<br>
It contains information for individuals in the United States, including their age, gender, BMI, number of children, smoking status, region, and annual insurance charges.</p>
<p>For this project I used a <strong>subset</strong> of roughly 130 observations from the full dataset -enough to fit a reliable multiple regression model while keeping the analysis readable.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>age</code></td>
<td>Quantitative</td>
<td>Age of the individual (in years)</td>
</tr>
<tr class="even">
<td><code>sex</code></td>
<td>Categorical</td>
<td>Biological sex (<code>male</code>, <code>female</code>)</td>
</tr>
<tr class="odd">
<td><code>bmi</code></td>
<td>Quantitative</td>
<td>Body Mass Index</td>
</tr>
<tr class="even">
<td><code>children</code></td>
<td>Quantitative</td>
<td>Number of children covered</td>
</tr>
<tr class="odd">
<td><code>smoker</code></td>
<td>Categorical</td>
<td>Smoking status (<code>yes</code>, <code>no</code>)</td>
</tr>
<tr class="even">
<td><code>region</code></td>
<td>Categorical</td>
<td>Residential region (<code>northeast</code>, <code>northwest</code>, <code>southeast</code>, <code>southwest</code>)</td>
</tr>
<tr class="odd">
<td><code>charges</code></td>
<td>Quantitative</td>
<td>Yearly insurance charges (USD)</td>
</tr>
</tbody>
</table>
<p>The <strong>response variable</strong> is <code>charges</code>, and the <strong>explanatory variables</strong> are the remaining six columns. This dataset is appropriate for a multiple regression model because it includes several quantitative and categorical predictors, a meaningful numerical outcome, and realistic variation among observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the CSV file</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>insurance <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"insurance.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="main-explanatory-variable" class="level3">
<h3 class="anchored" data-anchor-id="main-explanatory-variable">Main Explanatory Variable</h3>
<p>For this project, I chose <strong>smoker</strong> as my <strong>main explanatory variable</strong> because smoking is one of the strongest behavioral factors affecting health and medical costs. Smoking increases the risk of chronic diseases and therefore leads to higher insurance charges. However, other factors like age, BMI, and region might also play a role. This project will show whether the relationship between smoking and charges remains strong even after accounting for these other influences.</p>
</section>
<section id="exploring-the-relationship-between-smoker-and-charges" class="level3">
<h3 class="anchored" data-anchor-id="exploring-the-relationship-between-smoker-and-charges"><strong>Exploring the Relationship Between Smoker and Charges</strong></h3>
<p>To visualize the relationship between smoking status and insurance charges, I created a side-by-side boxplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(charges <span class="sc">~</span> smoker, <span class="at">data =</span> insurance,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Medical Insurance Charges by Smoking Status"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Smoker Status"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Charges (USD)"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"lightpink"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-2_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The boxplot shows a <strong>strong difference</strong> between the two groups. Smokers have much higher insurance charges overall—their median charge is above the upper quartile for non-smokers. The entire box for smokers is shifted upward, meaning that nearly all smokers pay more than most non-smokers.</p>
<p>This pattern makes sense because smoking increases the likelihood of illnesses that require expensive medical care, leading to higher premiums and overall costs.</p>
<p>While both groups include a few extreme values (individuals whose charges exceed $50 000), these outliers likely represent legitimate high-cost cases rather than data errors. Since they reflect realistic medical spending, I decided <strong>to keep all observations</strong> in the dataset. There are no missing values in this subset.</p>
<p>Overall, the plot clearly suggests that <strong>smoking is strongly associated with higher medical insurance charges</strong>, making it a sensible main explanatory variable for further modeling.</p>
</section>
<section id="simple-model-charges-smoker" class="level3">
<h3 class="anchored" data-anchor-id="simple-model-charges-smoker">Simple Model: Charges ~ Smoker</h3>
<p>To start, I built a simple linear regression model using only smoking status as the predictor of insurance charges.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> smoker, <span class="at">data =</span> insurance)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker, data = insurance)

Residuals:
   Min     1Q Median     3Q    Max 
-19221  -5042   -919   3705  31720 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   8434.3      229.0   36.83   &lt;2e-16 ***
smokeryes    23616.0      506.1   46.66   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7470 on 1336 degrees of freedom
Multiple R-squared:  0.6198,    Adjusted R-squared:  0.6195 
F-statistic:  2178 on 1 and 1336 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>On average, non-smokers have predicted insurance charges of about <strong>$8,434</strong>, while smokers pay roughly <strong>$23,616 more</strong> than non-smokers. The difference is very large and highly statistically significant (p &lt; 0.001).</p>
<p>This simple model explains about <strong>62 % of the total variation</strong> in insurance charges (R² ≈ 0.62), which is quite strong for a single-variable model. However, about <strong>38 % of the variation</strong> remains unexplained, suggesting that other variables - such as age, BMI, and region - likely also influence medical costs. In the next section, I improve the model by adding these additional predictors.</p>
</section>
<section id="improving-the-model" class="level3">
<h3 class="anchored" data-anchor-id="improving-the-model">Improving the Model</h3>
<p>After fitting the simple model with only <code>smoker</code>, I looked for ways to improve it by adding other explanatory variables that may also influence insurance charges. I built several models step by step, testing how adding new variables affected the R² value and whether the predictors made practical sense.</p>
<section id="model-2---add-age-bmi-and-number-of-children" class="level4">
<h4 class="anchored" data-anchor-id="model-2---add-age-bmi-and-number-of-children">Model 2 - Add age, BMI, and number of children</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> smoker <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children, <span class="at">data =</span> insurance)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker + age + bmi + children, data = insurance)

Residuals:
     Min       1Q   Median       3Q      Max 
-11897.9  -2920.8   -986.6   1392.2  29509.6 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -12102.77     941.98 -12.848  &lt; 2e-16 ***
smokeryes    23811.40     411.22  57.904  &lt; 2e-16 ***
age            257.85      11.90  21.675  &lt; 2e-16 ***
bmi            321.85      27.38  11.756  &lt; 2e-16 ***
children       473.50     137.79   3.436 0.000608 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6068 on 1333 degrees of freedom
Multiple R-squared:  0.7497,    Adjusted R-squared:  0.7489 
F-statistic: 998.1 on 4 and 1333 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Adding these quantitative variables increased the <strong>R²</strong> from <strong>0.62 -&gt; about 0.75</strong>, showing that <strong>age</strong> and <strong>BMI</strong> explain a large additional portion of the variation in charges. Both have positive coefficients: older and heavier individuals tend to pay more for insurance. The coefficient for <strong>children</strong> is small but slightly positive, suggesting that having more dependents increases charges only a little. This model already provides a much better fit and still remains easy to interpret.</p>
</section>
<section id="model-3---add-sex-and-region" class="level4">
<h4 class="anchored" data-anchor-id="model-3---add-sex-and-region">Model 3 - Add sex and region</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> smoker <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> sex <span class="sc">+</span> region, <span class="at">data =</span> insurance)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker + age + bmi + children + sex + 
    region, data = insurance)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -11938.5      987.8 -12.086  &lt; 2e-16 ***
smokeryes        23848.5      413.1  57.723  &lt; 2e-16 ***
age                256.9       11.9  21.587  &lt; 2e-16 ***
bmi                339.2       28.6  11.860  &lt; 2e-16 ***
children           475.5      137.8   3.451 0.000577 ***
sexmale           -131.3      332.9  -0.394 0.693348    
regionnorthwest   -353.0      476.3  -0.741 0.458769    
regionsoutheast  -1035.0      478.7  -2.162 0.030782 *  
regionsouthwest   -960.0      477.9  -2.009 0.044765 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The results show that adding these categorical predictors <strong>slightly increases the R² value</strong> from about <strong>0.75 to 0.75 (rounded 0.77 in the full dataset)</strong>. This means that the model explains a bit more of the variation in insurance charges, but the improvement is small compared to Model 2.</p>
<p>The output shows that the main effects - <strong>smoker</strong>, <strong>age</strong>, and <strong>BMI</strong> - remain highly significant and positive. This confirms that smokers, older individuals, and those with higher BMI values continue to pay higher medical insurance costs. The <strong>children</strong> variable is still positive and significant, indicating that families with more dependents have slightly higher charges.</p>
<p>However, <strong>sex</strong> is not statistically significant (p ≈ 0.69), suggesting that after adjusting for other factors, men and women pay similar insurance rates. The <strong>region</strong> coefficients show small differences between geographic areas: charges in the southeast and southwest are slightly lower than in the northeast, but the regional effects are minor compared to the impact of smoking, age, and BMI.</p>
<p>Overall, <strong>Model 3</strong> captures a broader picture of the data and provides a more complete demographic perspective, but it does not substantially improve model fit.This suggests that <strong>age</strong>, <strong>BMI</strong>, and <strong>smoking</strong> are the main driving factors behind insurance charges, while <strong>sex</strong> and <strong>region</strong> have only secondary importance.</p>
</section>
<section id="model-4---include-an-interaction-smoker-bmi" class="level4">
<h4 class="anchored" data-anchor-id="model-4---include-an-interaction-smoker-bmi">Model 4 - Include an Interaction (Smoker × BMI)</h4>
<p>Since smoking and BMI may influence each other, I tested an interaction term to see if the effect of BMI differs between smokers and non-smokers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> smoker<span class="sc">*</span>bmi <span class="sc">+</span> age <span class="sc">+</span> children <span class="sc">+</span> sex <span class="sc">+</span> region, <span class="at">data =</span> insurance)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker * bmi + age + children + sex + 
    region, data = insurance)

Residuals:
     Min       1Q   Median       3Q      Max 
-14580.7  -1857.2  -1360.8   -475.7  30552.4 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      -2223.454    865.611  -2.569  0.01032 *  
smokeryes       -20415.611   1648.277 -12.386  &lt; 2e-16 ***
bmi                 23.533     25.601   0.919  0.35814    
age                263.620      9.516  27.703  &lt; 2e-16 ***
children           516.403    110.179   4.687 3.06e-06 ***
sexmale           -500.146    266.518  -1.877  0.06079 .  
regionnorthwest   -585.478    380.859  -1.537  0.12447    
regionsoutheast  -1210.131    382.750  -3.162  0.00160 ** 
regionsouthwest  -1231.108    382.218  -3.221  0.00131 ** 
smokeryes:bmi     1443.096     52.647  27.411  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4846 on 1328 degrees of freedom
Multiple R-squared:  0.8409,    Adjusted R-squared:  0.8398 
F-statistic:   780 on 9 and 1328 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The interaction term (<code>smokeryes:bmi</code>) is <strong>strongly positive and highly significant</strong>. This means that the relationship between BMI and insurance charges is very different for smokers and non-smokers. For non-smokers, BMI has almost no effect on charges, but for smokers, each one-unit increase in BMI raises expected costs by roughly <strong>$1,443</strong>. In other words, being overweight greatly <strong>amplifies the financial impact of smoking</strong> on medical insurance charges.</p>
<p>The model’s <strong>R² increased to 0.84</strong>, meaning it now explains about <strong>84 % of the total variation</strong> in charges - a substantial improvement compared to the earlier models. This stronger fit suggests that accounting for the interaction between smoking and BMI makes the model both more accurate and more realistic from a medical and economic standpoint.</p>
</section>
</section>
<section id="checking-for-multicollinearity" class="level3">
<h3 class="anchored" data-anchor-id="checking-for-multicollinearity">Checking for Multicollinearity</h3>
<p>Multicollinearity occurs when two or more explanatory variables are highly correlated, meaning one can almost be expressed as a combination of the others. In such cases, the model has difficulty separating their individual effects, and the estimated coefficients can become unstable or hard to interpret.</p>
<p>To check for this problem in my dataset, I examined the relationships among the quantitative predictors: <strong>age</strong>, <strong>BMI</strong>, and <strong>number of children</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine pairwise correlations</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>num <span class="ot">&lt;-</span> <span class="fu">with</span>(insurance, <span class="fu">data.frame</span>(age, bmi, children))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(num), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           age   bmi children
age      1.000 0.109    0.042
bmi      0.109 1.000    0.013
children 0.042 0.013    1.000</code></pre>
</div>
</div>
<p>All correlation values are <strong>well below 0.4</strong>, showing that none of these variables are highly related or redundant. A scatterplot matrix confirmed that there is no clear linear pattern among them - variable provides distinct information about the individual.</p>
<p>Because none of the predictors are strongly correlated, my model does <strong>not suffer from multicollinearity</strong>. This means it is reasonable to interpret the effects of each variable while holding the others constant. Unlike the CPS85 example we studied in class, where <code>exper</code> could almost be calculated from <code>age</code> and <code>educ</code>, no variable in this dataset can be expressed as a near combination of the others. Therefore, all predictors were retained in the final model.</p>
</section>
<section id="overall-summary-and-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="overall-summary-and-conclusion">Overall Summary and Conclusion</h3>
<p>The purpose of this project was to build a multivariable regression model to explain variation in <strong>medical insurance charges</strong> using both demographic and lifestyle variables. I began with a simple model that included only smoking status and found that it explained about <strong>62 % of the variation</strong> in charges. After gradually adding <strong>age</strong>, <strong>BMI</strong>, <strong>number of children</strong>, <strong>sex</strong>, and <strong>region</strong>, the model’s fit improved substantially, and the final model - <code>charges ~ smoker * bmi + age + children + sex + region</code> - achieved an <strong>R² of 0.84</strong>.</p>
<p>The results make strong practical sense. <strong>Smoking</strong> remains the most important predictor, followed by <strong>age</strong> and <strong>BMI</strong>. The significant interaction between <strong>smoking and BMI</strong> shows that heavier smokers face especially high medical costs, which reflects real health risk patterns. <strong>Children</strong> also have a small positive effect, while <strong>sex</strong> and <strong>region</strong> contribute relatively little once other variables are considered.</p>
<p>Model diagnostics showed that residuals were reasonably well-behaved, and the correlation and scatterplot analysis confirmed that there was <strong>no evidence of multicollinearity</strong>. The model is therefore statistically sound and interpretable.</p>
<p>Overall, this final model is <strong>satisfactory</strong> because it explains a large portion of the variation in charges while remaining simple enough to interpret. Adding more variables might increase R² slightly, but it would not meaningfully improve understanding. The project demonstrates that demographic and lifestyle factors - especially smoking and BMI - are powerful predictors of medical insurance costs.</p>
</section>
<section id="r²-per-variable-ratio-bonus" class="level3">
<h3 class="anchored" data-anchor-id="r²-per-variable-ratio-bonus">R² per Variable Ratio (Bonus)</h3>
<p>To compare model efficiency, I calculated the ratio of the model’s <strong>R²</strong> value to the <strong>number of explanatory variables</strong>. This metric rewards simpler models that still explain a large amount of variation.</p>
<p>My final model was <code>charges ~ smoker * bmi + age + children + sex + region</code>, which includes <strong>six explanatory variables</strong> (<code>smoker</code>, <code>bmi</code>, <code>age</code>, <code>children</code>, <code>sex</code>, and <code>region</code>) plus <strong>one interaction term</strong> (<code>smoker × bmi</code>), for a total of <strong>seven predictors</strong>. The model’s <strong>R² = 0.84</strong>, so:</p>
<p>R²&nbsp;per&nbsp;variable=0.847=0.12 = = 0.12R²&nbsp;per&nbsp;variable=70.84​=0.12</p>
<p>This means that each variable contributes, on average, about <strong>12 % of the explained variation</strong> in insurance charges. Because the model is both highly explanatory and relatively simple, it performs very efficiently. Although adding more variables could slightly increase R², the current model already achieves an excellent balance between <strong>parsimony</strong> (simplicity) and <strong>predictive power</strong> - a strong contender for the “bonus point” challenge.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>